"""
Django settings for research_gpt project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3)-j%ulm-y&gxx%+$x13ci#rkwm51lhm&(7(%@)0v5$6#2m=rf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
NPM_BIN_PATH = r"C:\nvm4w\nodejs\npm.cmd"
TAILWIND_APP_NAME = 'theme'



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'research_gpt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'research_gpt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# touched on 2025-08-14T20:06:51.484891Z
# touched on 2025-08-14T20:06:54.017533Z
# touched on 2025-08-14T20:06:56.237737Z
# touched on 2025-08-14T20:06:58.342584Z
# touched on 2025-08-14T20:07:16.776182Z
# touched on 2025-08-14T20:07:19.247262Z
# touched on 2025-08-14T20:07:23.937808Z
# touched on 2025-08-14T20:07:35.229750Z
# touched on 2025-08-14T20:07:51.080264Z
# touched on 2025-08-14T20:07:53.384734Z
# touched on 2025-08-14T20:08:00.604871Z
# touched on 2025-08-14T20:08:04.837739Z
# touched on 2025-08-14T20:08:09.202739Z
# touched on 2025-08-14T20:08:15.516952Z
# touched on 2025-08-14T20:08:19.655123Z
# touched on 2025-08-14T20:08:21.906055Z
# touched on 2025-08-14T20:08:32.553496Z
# touched on 2025-08-14T20:08:36.858618Z
# touched on 2025-08-14T20:08:39.006361Z
# touched on 2025-08-14T20:08:45.294458Z
# touched on 2025-08-14T20:08:51.631233Z
# touched on 2025-08-14T20:08:55.901406Z
# touched on 2025-08-14T20:09:04.306691Z
# touched on 2025-08-14T20:09:14.850241Z
# touched on 2025-08-14T20:09:25.399083Z
# touched on 2025-08-14T20:09:40.996333Z
# touched on 2025-08-14T20:09:43.666817Z
# touched on 2025-08-14T20:09:47.851147Z
# touched on 2025-08-14T20:09:51.565936Z
# touched on 2025-08-14T20:09:53.648496Z
# touched on 2025-08-14T20:09:55.763612Z
# touched on 2025-08-14T20:10:16.775673Z
# touched on 2025-08-14T20:10:18.880731Z
# touched on 2025-08-14T20:10:26.981138Z
# touched on 2025-08-14T20:10:40.351490Z
# touched on 2025-08-14T20:10:46.548786Z
# touched on 2025-08-14T20:10:50.674079Z
# touched on 2025-08-14T20:10:57.655845Z
# touched on 2025-08-14T20:11:12.401890Z
# touched on 2025-08-14T20:11:14.485516Z
# touched on 2025-08-14T20:11:16.600067Z
# touched on 2025-08-14T20:11:30.738912Z
# touched on 2025-08-14T20:11:39.438286Z
# touched on 2025-08-14T20:11:48.067449Z
# touched on 2025-08-14T20:11:50.084719Z
# touched on 2025-08-14T20:11:52.262941Z
# touched on 2025-08-14T20:11:56.554649Z
# touched on 2025-08-14T20:11:58.744184Z
# touched on 2025-08-14T20:12:03.055933Z
# touched on 2025-08-14T20:12:13.302343Z
# touched on 2025-08-14T20:12:15.367682Z
# touched on 2025-08-14T20:12:17.467996Z
# touched on 2025-08-14T20:12:32.365266Z
# touched on 2025-08-14T20:12:40.615715Z
# touched on 2025-08-14T20:12:45.181550Z
# touched on 2025-08-14T20:13:01.963612Z